#!/bin/bash

export LANG=C

OUTPUT_DIR='.'
BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`
COMMIT_ID=`git rev-parse HEAD`
VERSION="$BRANCH_NAME - $COMMIT_ID"
cat >  "${OUTPUT_DIR}/Global/GitVersion.h" << EOF
#ifndef NATRON_GITVERSION_H_
#define NATRON_GITVERSION_H_
#define GIT_BRANCH "$BRANCH_NAME"
#define GIT_COMMIT "$COMMIT_ID"
#endif
EOF
exit
