"<!DOCTYPE html>\n"
"<!--[if IE 8]><html class=\"no-js lt-ie9\" lang=\"en\" > <![endif]-->\n"
"<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en\" > <!--<![endif]-->\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>__REPLACE_TITLE__ &mdash; NATRON_DOCUMENTATION</title>\n"
"<script type=\"text/javascript\" src=\"_static/js/modernizr.min.js\"></script>\n"
"<script type=\"text/javascript\" id=\"documentation_options\" data-url_root=\"./\" src=\"_static/documentation_options.js\"></script>\n"
"<script src=\"_static/jquery.js\"></script>\n"
"<script src=\"_static/underscore.js\"></script>\n"
"<script src=\"_static/doctools.js\"></script>\n"
"<script src=\"_static/language_data.js\"></script>\n"
"<script async=\"async\" src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS-MML_HTMLorMML\"></script>\n"
"<script type=\"text/javascript\" src=\"_static/js/theme.js\"></script>\n"
"<link rel=\"stylesheet\" href=\"_static/css/theme.css\" type=\"text/css\" />\n"
"<link rel=\"stylesheet\" href=\"_static/pygments.css\" type=\"text/css\" />\n"
"<link rel=\"stylesheet\" href=\"_static/theme_overrides.css\" type=\"text/css\" />\n"
"<link rel=\"index\" title=\"Index\" href=\"genindex.html\" />\n"
"<link rel=\"search\" title=\"Search\" href=\"search.html\" />\n"
"<link rel=\"next\" title=\"Preferences\" href=\"_prefs.html\" />\n"
"<link rel=\"prev\" title=\"Alternative Matte Extraction Tutorial\" href=\"guide/tutorials-AlternativeMatteExtraction.html\" />\n"
"</head>\n"
"<body class=\"wy-body-for-nav\">\n"
"<div class=\"wy-grid-for-nav\">\n"
"<nav data-toggle=\"wy-nav-shift\" class=\"wy-nav-side\">\n"
"<div class=\"wy-side-scroll\">\n"
"<div class=\"wy-side-nav-search\" >\n"
"<a href=\"index.html\" class=\"icon icon-home\"> Natron\n"
"<img src=\"_static/logo.png\" class=\"logo\" alt=\"Logo\"/>\n"
"</a>\n"
"<div class=\"version\">\n"
"2.3\n"
"</div>\n"
"<div role=\"search\">\n"
"<form id=\"rtd-search-form\" class=\"wy-form\" action=\"search.html\" method=\"get\">\n"
"<input type=\"text\" name=\"q\" placeholder=\"Search docs\" />\n"
"<input type=\"hidden\" name=\"check_keywords\" value=\"yes\" />\n"
"<input type=\"hidden\" name=\"area\" value=\"default\" />\n"
"</form>\n"
"</div>\n"
"</div>\n"
"<div class=\"wy-menu wy-menu-vertical\" data-spy=\"affix\" role=\"navigation\" aria-label=\"main navigation\">\n"
"<ul class=\"current\">\n"
