"</div>\n"
"</div>\n"
"</div>\n"
"<footer>\n"
"<hr/>\n"
"<div role=\"contentinfo\">\n"
"<p>\n"
"&copy; Copyright 2013-2022 The Natron documentation authors, licensed under CC BY-SA 4.0\n"
"</p>\n"
"</div>\n"
"Built with <a href=\"http://sphinx-doc.org/\">Sphinx</a> using a <a href=\"https://github.com/rtfd/sphinx_rtd_theme\">theme</a> provided by <a href=\"https://readthedocs.org\">Read the Docs</a>.\n"
"</footer>\n"
"</div>\n"
"</div>\n"
"</section>\n"
"</div>\n"
"<script type=\"text/javascript\">\n"
"jQuery(function () {\n"
"SphinxRtdTheme.Navigation.enable(true);\n"
"});\n"
"</script>\n"
"</body>\n"
"</html>\n"
