"<!DOCTYPE html>\n"
"<!--[if IE 8]><html class=\"no-js lt-ie9\" lang=\"en\" > <![endif]-->\n"
"<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en\" > <!--<![endif]-->\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>Preferences &mdash; NATRON_DOCUMENTATION</title>\n"
"<script type=\"text/javascript\" src=\"_static/js/modernizr.min.js\"></script>\n"
"<script type=\"text/javascript\" id=\"documentation_options\" data-url_root=\"./\" src=\"_static/documentation_options.js\"></script>\n"
"<script src=\"_static/jquery.js\"></script>\n"
"<script src=\"_static/underscore.js\"></script>\n"
"<script src=\"_static/doctools.js\"></script>\n"
"<script src=\"_static/language_data.js\"></script>\n"
"<script async=\"async\" src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS-MML_HTMLorMML\"></script>\n"
"<script type=\"text/javascript\" src=\"_static/js/theme.js\"></script>\n"
"<link rel=\"stylesheet\" href=\"_static/css/theme.css\" type=\"text/css\" />\n"
"<link rel=\"stylesheet\" href=\"_static/pygments.css\" type=\"text/css\" />\n"
"<link rel=\"stylesheet\" href=\"_static/theme_overrides.css\" type=\"text/css\" />\n"
"<link rel=\"index\" title=\"Index\" href=\"genindex.html\" />\n"
"<link rel=\"search\" title=\"Search\" href=\"search.html\" />\n"
"<link rel=\"next\" title=\"Environment Variables\" href=\"_environment.html\" />\n"
"<link rel=\"prev\" title=\"Reference Guide\" href=\"_group.html\" />\n"
"</head>\n"
"<body class=\"wy-body-for-nav\">\n"
"<div class=\"wy-grid-for-nav\">\n"
"<nav data-toggle=\"wy-nav-shift\" class=\"wy-nav-side\">\n"
"<div class=\"wy-side-scroll\">\n"
"<div class=\"wy-side-nav-search\" >\n"
"<a href=\"index.html\" class=\"icon icon-home\"> Natron\n"
"<img src=\"_static/logo.png\" class=\"logo\" alt=\"Logo\"/>\n"
"</a>\n"
"<div class=\"version\">\n"
"2.3\n"
"</div>\n"
"<div role=\"search\">\n"
"<form id=\"rtd-search-form\" class=\"wy-form\" action=\"search.html\" method=\"get\">\n"
"<input type=\"text\" name=\"q\" placeholder=\"Search docs\" />\n"
"<input type=\"hidden\" name=\"check_keywords\" value=\"yes\" />\n"
"<input type=\"hidden\" name=\"area\" value=\"default\" />\n"
"</form>\n"
"</div>\n"
"</div>\n"
"<div class=\"wy-menu wy-menu-vertical\" data-spy=\"affix\" role=\"navigation\" aria-label=\"main navigation\">\n"
"<ul class=\"current\">\n"
"<li class=\"toctree-l1\"><a class=\"reference internal\" href=\"guide/index.html\">User Guide</a></li>\n"
"<li class=\"toctree-l1 current\"><a class=\"reference internal\" href=\"_group.html\">Reference Guide</a><ul class=\"current\">\n"
"<li class=\"toctree-l2 current\"><a class=\"current reference internal\" href=\"#\">Preferences</a><ul>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#general\">General</a></li>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#threading\">Threading</a></li>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#rendering\">Rendering</a></li>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#gpu-rendering\">GPU Rendering</a></li>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#project-setup\">Project Setup</a></li>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#documentation\">Documentation</a></li>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#user-interface\">User Interface</a></li>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#color-management\">Color Management</a></li>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#caching\">Caching</a></li>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#viewer\">Viewer</a></li>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#nodegraph\">Nodegraph</a></li>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#plug-ins\">Plug-ins</a></li>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#python\">Python</a></li>\n"
"<li class=\"toctree-l3\"><a class=\"reference internal\" href=\"#appearance\">Appearance</a><ul>\n"
"<li class=\"toctree-l4\"><a class=\"reference internal\" href=\"#main-window\">Main Window</a></li>\n"
"<li class=\"toctree-l4\"><a class=\"reference internal\" href=\"#curve-editor\">Curve Editor</a></li>\n"
"<li class=\"toctree-l4\"><a class=\"reference internal\" href=\"#dope-sheet\">Dope Sheet</a></li>\n"
"<li class=\"toctree-l4\"><a class=\"reference internal\" href=\"#node-graph\">Node Graph</a></li>\n"
"<li class=\"toctree-l4\"><a class=\"reference internal\" href=\"#script-editor\">Script Editor</a></li>\n"
"</ul>\n"
"</li>\n"
"</ul>\n"
"</li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_environment.html\">Environment Variables</a></li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_groupImage.html\">Image nodes</a></li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_groupDraw.html\">Draw nodes</a></li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_groupTime.html\">Time nodes</a></li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_group%1.html\">%1 nodes</a></li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_groupColor.html\">Color nodes</a></li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_groupFilter.html\">Filter nodes</a></li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_groupKeyer.html\">Keyer nodes</a></li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_groupMerge.html\">Merge nodes</a></li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_groupTransform.html\">Transform nodes</a></li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_groupViews.html\">Views nodes</a></li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_groupOther.html\">Other nodes</a></li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_groupGMIC.html\">GMIC nodes</a></li>\n"
"<li class=\"toctree-l2\"><a class=\"reference internal\" href=\"_groupExtra.html\">Extra nodes</a></li>\n"
"</ul>\n"
"</li>\n"
"<li class=\"toctree-l1\"><a class=\"reference internal\" href=\"devel/index.html\">Developers Guide</a></li>\n"
"</ul>\n"
"</div>\n"
"</div>\n"
"</nav>\n"
"<section data-toggle=\"wy-nav-shift\" class=\"wy-nav-content-wrap\">\n"
"<nav class=\"wy-nav-top\" aria-label=\"top navigation\">\n"
"<i data-toggle=\"wy-nav-top\" class=\"fa fa-bars\"></i>\n"
"<a href=\"index.html\">Natron</a>\n"
"</nav>\n"
"<div class=\"wy-nav-content\">\n"
"<div class=\"rst-content\">\n"
"<div role=\"navigation\" aria-label=\"breadcrumbs navigation\">\n"
"<ul class=\"wy-breadcrumbs\">\n"
"<li><a href=\"index.html\">Docs</a> &raquo;</li>\n"
"<li><a href=\"_group.html\">Reference Guide</a> &raquo;</li>\n"
"<li>Preferences</li>\n"
"<li class=\"wy-breadcrumbs-aside\">\n"
"<a href=\"_sources/_prefs.rst.txt\" rel=\"nofollow\"> View page source</a>\n"
"</li>\n"
"</ul>\n"
"<hr/>\n"
"</div>\n"
"<div role=\"main\" class=\"document\" itemscope=\"itemscope\" itemtype=\"http://schema.org/Article\">\n"
"<div itemprop=\"articleBody\">\n"
"<div class=\"section\" id=\"preferences\">\n"
