# -*- mode: ruby -*-
# vi: set ft=ruby :

# VMs
Vagrant.configure(2) do |config|
  config.vm.define "centos" do |centos|
    centos.vm.box = "olear/centos65"
    centos.vm.box_check_update = true
    centos.vm.provider "virtualbox" do |vb|
      vb.memory = "3000"
      vb.cpus = 4
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end
  config.vm.define "macos" do |macos|
    macos.vm.box = "tuupola/osx-lion-10.7-xcode"
  end
  config.vm.define "windows" do |windows|
    windows.vm.box = "ferventcoder/win7pro-x64-nocm-lite"
  end
end
