#ifndef NATRON_GITVERSION_H_
#define NATRON_GITVERSION_H_
#define GIT_BRANCH "__BRANCH__"
#define GIT_COMMIT "__COMMIT__"
#define IO_GIT_COMMIT "__IO_COMMIT__"
#define MISC_GIT_COMMIT "__MISC_COMMIT__"
#define ARENA_GIT_COMMIT "__ARENA_COMMIT__"
#endif

