# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "olear/centos65"
  config.vm.box_check_update = true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3000"
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end
end
