#############################################################################
# Makefile for building: libopenMVG.a
# Generated by qmake (2.01a) (Qt 4.8.7) on: Thu Mar 24 12:42:38 2016
# Project:  openMVG.pro
# Template: lib
# Command: /opt/local/libexec/qt4/bin/qmake -spec /opt/local/libexec/qt4/share/mkspecs/macx-xcode CONFIG+=debug -o openMVG.xcodeproj/project.pbxproj openMVG.pro
#############################################################################

QMAKE    = /opt/local/libexec/qt4/bin/qmake
openMVG.xcodeproj/project.pbxproj: openMVG.pro  /opt/local/libexec/qt4/share/mkspecs/macx-xcode/qmake.conf /opt/local/libexec/qt4/share/mkspecs/common/unix.conf \
		/opt/local/libexec/qt4/share/mkspecs/common/mac.conf \
		/opt/local/libexec/qt4/share/mkspecs/common/gcc-base.conf \
		/opt/local/libexec/qt4/share/mkspecs/common/gcc-base-macx.conf \
		/opt/local/libexec/qt4/share/mkspecs/common/g++-base.conf \
		/opt/local/libexec/qt4/share/mkspecs/common/g++-macx.conf \
		/opt/local/libexec/qt4/share/mkspecs/qconfig.pri \
		/opt/local/libexec/qt4/share/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/libexec/qt4/share/mkspecs/features/qt_functions.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/qt_config.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/exclusive_builds.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/default_pre.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/mac/default_pre.prf \
		../global.pri \
		../config.pri \
		/opt/local/libexec/qt4/share/mkspecs/features/debug.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/default_post.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/mac/default_post.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/mac/objective_cxx.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/mac/objective_c.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/mac/split_sources.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/link_pkgconfig.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/warn_on.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/staticlib.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/static.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/mac/x86_64.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/mac/rez.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/mac/sdk.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/resources.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/uic.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/yacc.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/lex.prf \
		/opt/local/libexec/qt4/share/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /opt/local/libexec/qt4/share/mkspecs/macx-xcode CONFIG+=debug -o openMVG.xcodeproj/project.pbxproj openMVG.pro
/opt/local/libexec/qt4/share/mkspecs/common/unix.conf:
/opt/local/libexec/qt4/share/mkspecs/common/mac.conf:
/opt/local/libexec/qt4/share/mkspecs/common/gcc-base.conf:
/opt/local/libexec/qt4/share/mkspecs/common/gcc-base-macx.conf:
/opt/local/libexec/qt4/share/mkspecs/common/g++-base.conf:
/opt/local/libexec/qt4/share/mkspecs/common/g++-macx.conf:
/opt/local/libexec/qt4/share/mkspecs/qconfig.pri:
/opt/local/libexec/qt4/share/mkspecs/modules/qt_webkit_version.pri:
/opt/local/libexec/qt4/share/mkspecs/features/qt_functions.prf:
/opt/local/libexec/qt4/share/mkspecs/features/qt_config.prf:
/opt/local/libexec/qt4/share/mkspecs/features/exclusive_builds.prf:
/opt/local/libexec/qt4/share/mkspecs/features/default_pre.prf:
/opt/local/libexec/qt4/share/mkspecs/features/mac/default_pre.prf:
../global.pri:
../config.pri:
/opt/local/libexec/qt4/share/mkspecs/features/debug.prf:
/opt/local/libexec/qt4/share/mkspecs/features/default_post.prf:
/opt/local/libexec/qt4/share/mkspecs/features/mac/default_post.prf:
/opt/local/libexec/qt4/share/mkspecs/features/mac/objective_cxx.prf:
/opt/local/libexec/qt4/share/mkspecs/features/mac/objective_c.prf:
/opt/local/libexec/qt4/share/mkspecs/features/mac/split_sources.prf:
/opt/local/libexec/qt4/share/mkspecs/features/link_pkgconfig.prf:
/opt/local/libexec/qt4/share/mkspecs/features/warn_on.prf:
/opt/local/libexec/qt4/share/mkspecs/features/staticlib.prf:
/opt/local/libexec/qt4/share/mkspecs/features/static.prf:
/opt/local/libexec/qt4/share/mkspecs/features/mac/x86_64.prf:
/opt/local/libexec/qt4/share/mkspecs/features/mac/rez.prf:
/opt/local/libexec/qt4/share/mkspecs/features/mac/sdk.prf:
/opt/local/libexec/qt4/share/mkspecs/features/resources.prf:
/opt/local/libexec/qt4/share/mkspecs/features/uic.prf:
/opt/local/libexec/qt4/share/mkspecs/features/yacc.prf:
/opt/local/libexec/qt4/share/mkspecs/features/lex.prf:
/opt/local/libexec/qt4/share/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /opt/local/libexec/qt4/share/mkspecs/macx-xcode CONFIG+=debug -o openMVG.xcodeproj/project.pbxproj openMVG.pro

