#ifndef YAML_VERSION_H_62B23520_7C8E_11DE_8A39_0800200C9A66
#define YAML_VERSION_H_62B23520_7C8E_11DE_8A39_0800200C9A66

#define YAML_VERSION_MAJOR 0
#define YAML_VERSION_MINOR 5
#define YAML_VERSION_REVISION 3

#define YAML_VERSION_ENCODE(major, minor, revision) ( \
( (major) * 10000 ) \
+ ( (minor) * 100 )  \
+ ( (revision) * 1 ) )

#define YAML_VERSION_ENCODED YAML_VERSION_ENCODE( \
YAML_VERSION_MAJOR, \
YAML_VERSION_MINOR, \
YAML_VERSION_REVISION)

#define YAML_VERSION_STRINGIZE_(major, minor, revision) \
# major "." # minor "." # revision

#define YAML_VERSION_STRINGIZE(major, minor, revision) \
YAML_VERSION_STRINGIZE_(major, minor, revision)

#define YAML_VERSION_STRING YAML_VERSION_STRINGIZE( \
YAML_VERSION_MAJOR, \
YAML_VERSION_MINOR, \
YAML_VERSION_REVISION)


#define YAML_NAMESPACE YAML # YAML_VERSION_MAJOR # YAML_VERSION_MINOR # YAML_VERSION_REVISION
#define YAML_NAMESPACE_ENTER namespace YAML_NAMESPACE {
#define YAML_NAMESPACE_EXIT }
#define YAML_NAMESPACE_USING using namespace YAML_NAMESPACE;

#endif  // YAML_VERSION_H_62B23520_7C8E_11DE_8A39_0800200C9A66
