#############################################################################
# Makefile for building: NatronRenderer
# Generated by qmake (2.01a) (Qt 4.8.5) on: Mon Feb 17 14:22:15 2014
# Project:  Renderer.pro
# Template: app
# Command: /opt/local/bin/qmake -spec /opt/local/share/qt4/mkspecs/macx-xcode CONFIG+=debug -o NatronRenderer.xcodeproj/project.pbxproj Renderer.pro
#############################################################################

QMAKE    = /opt/local/bin/qmake
NatronRenderer.xcodeproj/project.pbxproj: Renderer.pro  /opt/local/share/qt4/mkspecs/macx-xcode/qmake.conf /opt/local/share/qt4/mkspecs/common/unix.conf \
		/opt/local/share/qt4/mkspecs/common/mac.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf \
		/opt/local/share/qt4/mkspecs/common/g++-base.conf \
		/opt/local/share/qt4/mkspecs/common/g++-macx.conf \
		/opt/local/share/qt4/mkspecs/qconfig.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt4/mkspecs/features/qt_config.prf \
		/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt4/mkspecs/features/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf \
		../global.pri \
		../config.pri \
		/opt/local/share/qt4/mkspecs/features/debug.prf \
		/opt/local/share/qt4/mkspecs/features/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_cxx.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt4/mkspecs/features/mac/split_sources.prf \
		/opt/local/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/opt/local/share/qt4/mkspecs/features/warn_on.prf \
		/opt/local/share/qt4/mkspecs/features/qt.prf \
		/opt/local/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt4/mkspecs/features/moc.prf \
		/opt/local/share/qt4/mkspecs/features/shared.prf \
		/opt/local/share/qt4/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt4/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt4/mkspecs/features/resources.prf \
		/opt/local/share/qt4/mkspecs/features/uic.prf \
		/opt/local/share/qt4/mkspecs/features/yacc.prf \
		/opt/local/share/qt4/mkspecs/features/lex.prf \
		/opt/local/share/qt4/mkspecs/features/include_source_dir.prf \
		/opt/local/Library/Frameworks/QtNetwork.framework/QtNetwork.prl \
		/opt/local/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /opt/local/share/qt4/mkspecs/macx-xcode CONFIG+=debug -o NatronRenderer.xcodeproj/project.pbxproj Renderer.pro
/opt/local/share/qt4/mkspecs/common/unix.conf:
/opt/local/share/qt4/mkspecs/common/mac.conf:
/opt/local/share/qt4/mkspecs/common/gcc-base.conf:
/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf:
/opt/local/share/qt4/mkspecs/common/g++-base.conf:
/opt/local/share/qt4/mkspecs/common/g++-macx.conf:
/opt/local/share/qt4/mkspecs/qconfig.pri:
/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/opt/local/share/qt4/mkspecs/features/qt_functions.prf:
/opt/local/share/qt4/mkspecs/features/qt_config.prf:
/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf:
/opt/local/share/qt4/mkspecs/features/default_pre.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf:
../global.pri:
../config.pri:
/opt/local/share/qt4/mkspecs/features/debug.prf:
/opt/local/share/qt4/mkspecs/features/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/x86_64.prf:
/opt/local/share/qt4/mkspecs/features/mac/objective_cxx.prf:
/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf:
/opt/local/share/qt4/mkspecs/features/mac/split_sources.prf:
/opt/local/share/qt4/mkspecs/features/link_pkgconfig.prf:
/opt/local/share/qt4/mkspecs/features/warn_on.prf:
/opt/local/share/qt4/mkspecs/features/qt.prf:
/opt/local/share/qt4/mkspecs/features/unix/thread.prf:
/opt/local/share/qt4/mkspecs/features/moc.prf:
/opt/local/share/qt4/mkspecs/features/shared.prf:
/opt/local/share/qt4/mkspecs/features/mac/rez.prf:
/opt/local/share/qt4/mkspecs/features/mac/sdk.prf:
/opt/local/share/qt4/mkspecs/features/resources.prf:
/opt/local/share/qt4/mkspecs/features/uic.prf:
/opt/local/share/qt4/mkspecs/features/yacc.prf:
/opt/local/share/qt4/mkspecs/features/lex.prf:
/opt/local/share/qt4/mkspecs/features/include_source_dir.prf:
/opt/local/Library/Frameworks/QtNetwork.framework/QtNetwork.prl:
/opt/local/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/local/share/qt4/mkspecs/macx-xcode CONFIG+=debug -o NatronRenderer.xcodeproj/project.pbxproj Renderer.pro

